about/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path

# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
    path('delete/<comment_id>', views.delete_item, name='delete'),
    path('edit/<comment_id>', views.edit_item, name='edit')
]

contact/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'contact'

urlpatterns = [
    path('', views.contact_us, name='contact_us'),
]

home/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # connects the main urls with the app urls
    path('', include('home.urls', namespace='home')),
    path('meals/', include('meals.urls', namespace='meals')),
    path('make_booking/', include('bookings.urls', namespace='bookings')),
    path('contact_us/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.db import models
from django.contrib.auth.models import User

# Internal:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class About(models.Model):
    """
    A class for the about model
    """
    title = models.CharField(
        max_length=50
        )
    body = models.TextField(
        max_length=1000
        )
    image = models.ImageField(
        upload_to='about/'
        )

    class Meta:
        verbose_name = 'About'
        verbose_name_plural = 'About'

    def __str__(self):
        """
        Returns the about name string
        """
        return self.title


class Reason(models.Model):
    """
    A class for the reason model
    """
    title = models.CharField(
        max_length=50
        )
    body = models.TextField(
        max_length=500
        )

    class Meta:
        verbose_name = 'Reason'
        verbose_name_plural = 'Reasons'

    def __str__(self):
        """
        Returns the about name string
        """
        return self.title


class Chef(models.Model):
    """
    A class for the chef model
    """
    name = models.CharField(
        max_length=30
        )
    description = models.TextField(
        max_length=300
        )
    image = models.ImageField(
        upload_to='about/'
        )

    class Meta:
        verbose_name = 'Chef'
        verbose_name_plural = 'Chefs'

    def __str__(self):
        """
        Returns the chef name string
        """
        return self.name


class Comment(models.Model):
    """
    A class for the comment model
    """
    name = models.CharField(
        max_length=80
        )
    email = models.EmailField()
    body = models.TextField(500)
    created_on = models.DateTimeField(
        auto_now_add=True
        )
    approved = models.BooleanField(
        default=False
        )

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'        
        ordering = ["created_on"]

    def __str__(self):
        """
        Returns comment body and name as a string
        """
        return f"Comment {self.body} by {self.name}"

about/forms.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django import forms
# Internal:
from .models import Comment
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class CommentForm(forms.ModelForm):
    """
    A class for Comment forms
    """
    class Meta:
        model = Comment
        fields = ('body',)

about/views.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic

# Internal:
from .models import About, Chef, Reason, Comment
from .forms import CommentForm
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


def about(request):
    """
    A view to show restaurant bio,
    reasons to dine, chef images and bio,
    and comments
    Args:
        request (object): HTTP request object and or form object.
    Returns:
        Render of items page with context
    """
    about = About.objects.all()
    chefs = Chef.objects.all()
    reasons = Reason.objects.all()
    comments = Comment.objects.filter(
        approved=True
        ).order_by(
            "-created_on"
        )
    comment_form = CommentForm()
    commented = False
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.save()
            commented = True
        else:
            comment_form = CommentForm()
    context = {
        'about': about,
        'chefs': chefs,
        'reasons': reasons,
        'comment_form': comment_form,
        'comments': comments,
        'commented': commented,
        }
    return render(request, 'about.html', context)


def edit_item(request, comment_id):
    """
    A view to editing comments
    """
    comment = get_object_or_404(Comment, id=comment_id)
    comment.approved = False
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('/about/')
    form = CommentForm(instance = comment)
    context = {
        'form':form
    }
    return render(request, 'edit_comment.html', context)


def delete_item(request, comment_id):
    """
    A view delete comments
    Args:
        request (object): HTTP request object.
        comment_id: the unique numeric identifier of the comment to be deleted
    Returns:
        Redirect to about page with comment removed
    """
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == 'POST':
        comment.delete()
        return redirect('/about/')
    context = {'comment': comment}
    return render(request, 'delete_comment.html', context)

about/templates/about.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<section class = "banner">
    <!--Photo by <a href="https://unsplash.com/@jaywennington?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jay Wennington</a> on <a href="https://unsplash.com/s/photos/restaurant?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  -->
    <div id = "about-banner" class="d-flex flex-column container-fluid justify-content-center align-items-center white-text">
        <h1 class = "heading-font font-size-96 white-text">About Us</h1>
    </div>
</section>
<section class = "margin-top-10vh">
    <div class="container">
        {% for about in about %}
        <div class="row">
            <div class="col-sm">
                <img src="{{ about.image.url }}" alt="restaurant image" class="img-fluid" style="margin-top:2%;">
            </div>
            <div class="col-md relative">
                <div class="row">
                    <div class="col">
                        <h2 style = "position:relative;"> {{ about.title }}</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {{ about.body|linebreaks }}
                        <p class = "font-size-larger mt-5">Find us <a href = "{% url 'contact:contact_us' %}">here</a></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<section class = "margin-top-10vh">
    <div class="container">
        <div class="row">
            <div class="col-md">
                <div class="row">
                    <div class="col">
                        <h2>Why Choose Us</h2>
                    </div>
                </div>       
                <div class="row">
                    <div class="col">
                        <div class="accordion accordion-flush" id="accordionFlushExample">
                            {% for reason in reasons %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ reason.title }}
                                    </button>
                                </h2>
                                <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionFlushExample">
                                    <div class="accordion-body">
                                        {{ reason.body }}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div id="reasons-carousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#reasons-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#reasons-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#reasons-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://res.cloudinary.com/dannymagnus/image/upload/v1648460410/static/img/ingredients3.d1d17b408f87.jpg" class="d-block w-100" alt="great atmosphere">
                        </div>
                        <div class="carousel-item">
                            <img src="https://res.cloudinary.com/dannymagnus/image/upload/v1648460410/static/img/atmosphere.f5da57cc72d2.jpg" class="d-block w-100" alt="fresh ingredients">
                        </div>
                        <div class="carousel-item">
                            <img src="https://res.cloudinary.com/dannymagnus/image/upload/v1648460409/static/img/staff.b94457000f76.jpg" class="d-block w-100" alt="friendly staff">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#reasons-carousel" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#reasons-carousel" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Section to display chefs-->
<section id = "chefs" class = "margin-top-10vh">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class = "text-align-center">
                    Our Chefs
                </h2>
            </div>
        </div>
        <div class="row margin-top-10vh">
            {% for chef in chefs %}
            <div class="col-sm">
                <div class="row">
                    <div class="col">
                        <img src="{{ chef.image.url }}" alt="{{ chef.name }}" class="img-fluid">
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col">
                        <h3>{{ chef.name }}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col margin-bottom-10vh">
                        <p>
                            {{ chef.description }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class = margin-bottom-10vh>
    <div class="container">
        <h1 class = "heading-font font-size-96">Comments</h1>
    </div>
    <div class="container max-height-400 overflow-auto">
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        {% for comment in comments %}
            <div class="row">
                <div class="col-sm">
                    <p>
                    <strong> Posted by: {{ comment.name }}</strong>
                    </p>
                </div>   
                <div class="col-sm">
                    <p>
                    Posted on: {{ comment.created_on }}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p>Comment</p>
                    <p>{{ comment.body }}</p>
                </div>
            </div>
            {% if user.is_authenticated %}
            {% if user.username == comment.name %}
            <div class="row">
                <div class="col">
                    <a href="{% url 'about:edit' comment.id %}" class="btn btn-signup btn-md">Edit</a>
                    <a href="{% url 'about:delete' comment.id %}" class="btn btn-signup btn-md">Delete</a>
                </div>
            </div>
            {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <!--Comments section-->
    <div class="container">
        <div class="row">
            <div class="col-6">
                <!-- Validate if already commented -->
                {% if commented %}
                    <div class="alert alert-success">
                        Your comment is awaiting approval.
                    </div>
                {% else %}
                <!-- User has to be logged in -->
                {% if user.is_authenticated %}
                    <h3>Leave a comment:</h3>
                    <p>Posting as: {{ user.username }}</p>
                    <form method = "POST" style = "margin-top: 1.3em;">
                        {{comment_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class = "btn btn-signup btn-lg">Submit</button>
                    </form>
                {% else %}
                    <p>To leave a comment please <a href="{% url 'account_login' %}">Login</a> or <a href="{% url 'account_signup' %}">Signup</a></p>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
    <script src="{% static 'about/js/about.js' %}"></script>
{% endblock %}

about/templates/delete_comment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<section class = "banner">
    <div id = "about-banner" class="d-flex flex-column container-fluid justify-content-center align-items-center white-text">
        <h1 class = "heading-font font-size-96 white-text">About Us</h1>
    </div>
</section>
<section class = "margin-bottom-10vh margin-top-10vh">
    <div class="container">
        <h1 class = "heading-font font-size-96">Comments</h1>
    </div>
    <div class="container max-height-400 overflow-auto">
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class = "row">
            <div class="col-md-6">
                <form action "." method = "POST">{% csrf_token %}
                    <p>Are you sure you want to delete comment {{ comment }}</p>
                    <button class="btn btn-signup btn-md" type="submit">Delete</button>
                    <a href = "/about/" class="btn btn-signup btn-md">Cancel</a>
                </form>
            </div>
        </div>
</section>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
    <script src="{% static 'about/js/carousel.js' %}"></script>
{% endblock %}

about/templates/edit_comment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section class = "banner">
    <!--Photo by <a href="https://unsplash.com/@jaywennington?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jay Wennington</a> on <a href="https://unsplash.com/s/photos/restaurant?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  -->
    <div id = "about-banner" class="d-flex flex-column container-fluid justify-content-center align-items-center white-text">
        <h1 class = "heading-font font-size-96 white-text">About Us</h1>
    </div>
</section>
<section class = "margin-bottom-10vh margin-top-10vh">
    <div class="container">
        <h1 class = "heading-font font-size-96">Comments</h1>
    </div>
    <div class="container max-height-400 overflow-auto">
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class = "row">
            <div class="col-md-6">
                <h1>Edit your comment</h1>
                <form method = "POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                <div>
                    <p>
                        <button class="btn btn-signup btn-md" type = "submit">Update Item</button>
                    </p>
                </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
    <script src="{% static 'about/js/carousel.js' %}"></script>
{% endblock %}