home/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

meals/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Provide an app name to fix namespace error
app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('lunch_menu', views.lunch_menu, name='lunch_menu'),
    path('dinner_menu', views.dinner_menu, name='dinner_menu'),
    path('drinks_menu', views.drinks_menu, name='drinks_menu'),
    path('<slug>', views.meal_information, name='meal_information'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # connects the main urls with the app urls
    path('', include('home.urls', namespace='home')),
    path('meals/', include('meals.urls', namespace='meals')),
    path('make_booking/', include('bookings.urls', namespace='bookings')),
    path('contact_us/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/models.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.db import models
from django.utils.text import slugify
from django.contrib import admin

# Internal:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class Allergen(models.Model):
    """
    A class for the allergen model
    """
    name = models.CharField(
        max_length=50
        )
    image = models.ImageField(
        upload_to='allergens/',
        blank=True
        )
    
    class Meta:
        verbose_name = 'Allergen'
        verbose_name_plural = 'Allergens'

    def __str__(self):
        return self.name


class Meal(models.Model):
    """
    A class for the meal model
    """
    name = models.CharField(
        max_length=50
        )
    description = models.TextField(
        max_length=500
        )
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='category',
        related_query_name='category'
        )
    lunch = models.BooleanField(
        default=False
        )
    dinner = models.BooleanField(
        default=False
        )
    calories = models.IntegerField(
        default=500
        )
    price = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        )
    vegetarian = models.BooleanField(
        default=False
        )
    vegan = models.BooleanField(
        default=False
        )
    allergens = models.ManyToManyField(
        Allergen, blank=True,
        related_name='allergens'
        )
    image = models.ImageField(
        upload_to='meals/',
        blank=True
        )
    slug = models.SlugField(
        blank=True,
        null=True
        )
    
    class Meta:
        verbose_name = 'Meal'
        verbose_name_plural = 'Meals'

    # Overide save function to create a slug on save -
    # courtesy of Mahmoud Ahmed
    def save(self, *args, **kwargs):
        """
        Function to take slug or create on if none exist
        """
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meal, self).save(*args, **kwargs)

    # Show object by name in admin panel
    def __str__(self):
        """
        Returns the category name string
        Args:
            self (object): self.
        Returns:
            The category name string
        """
        return self.name


class Category(models.Model):
    """
    A class for the category model
    """
    name = models.CharField(
        max_length=50
        )
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        """
        Returns the category name string
        Args:
            self (object): self.
        Returns:
            The category name string
        """
        return self.name


class Drink(models.Model):
    """
    A class for the drink model
    """
    name = models.CharField(
        max_length=50
        )
    category = models.ForeignKey(
        'DrinkCategory',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='category',
        related_query_name='category'
        )
    description = models.CharField(
        max_length=100,
        blank=True
        )
    
    class Meta:
        verbose_name = 'Drink'
        verbose_name_plural = 'Drinks'

    def __str__(self):
        """
        Returns the category name string
        Args:
            self (object): self.
        Returns:
            The category name string
        """
        return self.name


class DrinkCategory(models.Model):
    """
    A class for the drinkcategory model
    """
    name = models.CharField(
        max_length=50
        )
    
    class Meta:
        verbose_name = 'Drink Category'
        verbose_name_plural = 'Drink Categories'

    def __str__(self):
        """
        Returns the category name string
        Args:
            self (object): self.
        Returns:
            The category name string
        """
        return self.name

meals/views.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.shortcuts import render, redirect, get_object_or_404

# Internal:
from .models import Meal, Category, Allergen, Drink, DrinkCategory
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


def meal_list(request):
    """
    A view to show all products
    Args:
        request (object): HTTP request object.
    Returns:
        Render of products page with context
    """
    meal_list = Meal.objects.all()
    categories = Category.objects.all()
    allergens = Allergen.objects.all()

    context = {'meal_list': meal_list,
               'categories': categories,
               'allergens': allergens
               }

    return render(request, 'Meals/meal_list.html', context)


def lunch_menu(request):
    """
    A view to show all lunch products, filtered by boolean field
    Args:
        request (object): HTTP request object.
    Returns:
        Render of products page with context
    """
    meal_list = Meal.objects.all()
    categories = Category.objects.all()
    allergens = Allergen.objects.all()

    context = {'meal_list': meal_list,
               'categories': categories,
               'allergens': allergens
               }

    return render(request, 'Meals/lunch_menu.html', context)


def dinner_menu(request):
    """
    A view to show all dinner products, filtered by boolean field
    Args:
        request (object): HTTP request object.
    Returns:
        Render of products page with context
    """
    meal_list = Meal.objects.all()
    categories = Category.objects.all()
    allergens = Allergen.objects.all()

    context = {'meal_list': meal_list,
               'categories': categories,
               'allergens': allergens
               }

    return render(request, 'Meals/dinner_menu.html', context)


def drinks_menu(request):
    """
    A view to show all drink products
    Args:
        request (object): HTTP request object.
    Returns:
        Render of products page with context
    """
    drinks = Drink.objects.all()
    categories = DrinkCategory.objects.all()

    context = {'drinks': drinks,
               'categories': categories,
               }

    return render(request, 'Meals/drinks_menu.html', context)


# takes the request and slug parameter from urls.py
def meal_information(request, slug):
    """
    A view to detailed meal view, all meal information
    Args:
        request (object): HTTP request object.
    Returns:
        Render of products page with context
    """
    meal_information = get_object_or_404(Meal, slug=slug)
    context = {'meal_information': meal_information}
    return render(request, 'Meals/meal_information.html', context)

meals/templates/Meals/dinner_menu.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<section class = "banner">
    <!--Photo by <a href="https://unsplash.com/@jaywennington?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jay Wennington</a> on <a href="https://unsplash.com/s/photos/restaurant?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  -->
    <div id = "full-menu-header" class="container">
        <div class="row margin-top-5vh">
            <div class="col-sm col-md4"></div>
            <div class="col-sm col-md4 d-flex align-items-center justify-content-center border-right-2 border-left-2">
                <h2 class = "text-align-center border-left-2px">Dinner Menu</h2>
            </div>
            <div class="col-sm col-md4"></div>
        
        </div>
    </div>

    <div class="relative">
        <div class="container horizontal-scroll d-flex overflow-auto">
            {% for category in categories %}
                <a href="#{{ category.name}}">{{category.name}}</a>
                <div class="container">
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class = "margin-bottom-10vh">
    {% for category in categories %}
        <div>
            <hr class="full-width-2px">
        </div>
        <div id = "{{category.name}}" class = "container-fluid d-flex align-items-center justify-content-center menu-category-background-generic {{category.name}}">
            <h1 class = "heading-font font-size-72">{{category.name}}</h1>
        </div>
        <div>
            <hr class="full-width-2px">
        </div>
        <div class="container">        
            <div class="row">
                {% for meal in meal_list %}
                    {% if meal.dinner %}
                        {% if meal.category.name == category.name %}
                            <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 col-xxl-4 menu-item">
                                <div class="row">
                                    <div class="col-4 padding-0">
                                        <a href="{% url 'meals:meal_information' meal.slug %}"><img src="{{meal.image.url}}" alt = "{{meal.name}}" class="img-fluid menu-item-image"></a>
                                    </div>
                                    <div class="col-8">
                                        <div class="row height-20">
                                            <div class="col">
                                                <p>{{meal.name}}</p>
                                            </div>
                                        </div>
                                        <div class="row height-60">
                                            <div class="col">
                                                <p class = "description-overflow-scroll">
                                                    {{meal.description}}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="row meal-summary height-20">
                                            <div class="col">
                                                <p>
                                                    £{{meal.price}}
                                                </p>
                                            </div>
                                            <div class="col">
                                                <div class = "{% if not meal.vegan and not meal.vegetarian %} transparent {% endif %}">
                                                    {% if meal.vegan %} 
                                                        <div class="dark-circle-background white-text">
                                                            Ve
                                                        </div>
                                                    {% endif %}
                                                    {% if meal.vegetarian %}
                                                        <div class="dark-circle-background white-text">
                                                            V 
                                                        </div>
                                                    {% endif %}
                                                    {% if not meal.vegan and not meal.vegetarian %}
                                                        Has Meat
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</section>


{% endblock %}

meals/templates/Meals/drinks_menu.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<section class = "banner">
    <div id = "full-menu-header" class="container">
        <div class="row margin-top-5vh">
            <div class="col-sm col-md4"></div>
            <div class="col-sm col-md4 d-flex align-items-center justify-content-center border-right-2 border-left-2">
                <h2 class = "text-align-center border-left-2px">Drinks Menu</h2>
            </div>
            <div class="col-sm col-md4"></div>        
        </div>
    </div>
    <div>
        <hr class="full-width-2px">
    </div>
    {% for category in categories %}

        <div class = "container d-flex align-items-center {{category.name}} margin-top-10vh border-bottom-4 pb-2">
            <h2 class = "heading-font font-size-48">{{category.name}}</h2>
        </div>
        <div class="container">        
            <div class="row">
                {% for drink in drinks %}
                        {% if drink.category.name == category.name %}
                            <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 col-xxl-4 menu-item">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="row">
                                            <div class="col">
                                                <p>{{drink.name}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <p>
                                                    {{drink.description}}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <div class = "margin-bottom-10vh">
    </div>
</section>


{% endblock %}

meals/templates/Meals/lunch_menu.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<section class = "banner">
    <div id = "full-menu-header" class="container">
        <div class="row margin-top-5vh">
            <div class="col-sm col-md4"></div>
            <div class="col-sm col-md4 d-flex align-items-center justify-content-center border-right-2 border-left-2">
                <h2 class = "text-align-center border-left-2px">Lunch Menu</h2>
            </div>
            <div class="col-sm col-md4"></div>            
        </div>
    </div>
    <div>
        <div class="relative">
            <div class="container horizontal-scroll d-flex overflow-auto">
                {% for category in categories %}
                <a href="#{{ category.name}}">{{category.name}}</a>
                <div class="container">
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<section class = "content">
<div class = "margin-bottom-10vh">
{% for category in categories %}
    <div>
        <hr class="full-width-2px">
    </div>
    <div id = "{{category.name}}" class = "container-fluid d-flex align-items-center justify-content-center menu-category-background-generic {{category.name}}">
        <h1 class = "heading-font font-size-72">{{category.name}}</h1>
    </div>
    <div>
        <hr class="full-width-2px">
    </div>
    <div class="container">        
        <div class="row">
            {% for meal in meal_list %}
                {% if meal.lunch %}
                    {% if meal.category.name == category.name %}
                        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 col-xxl-4 menu-item">
                            <div class="row">
                                <div class="col-4 padding-0">
                                    <a href="{% url 'meals:meal_information' meal.slug %}"><img src="{{meal.image.url}}" alt = "{{meal.name}}" class="img-fluid menu-item-image"></a>
                                </div>
                                <div class="col-8">
                                    <div class="row height-20">
                                        <div class="col">
                                            <p>{{meal.name}}</p>
                                        </div>
                                    </div>
                                    <div class="row height-60">
                                        <div class="col">
                                            <p class = "description-overflow-scroll">
                                                {{meal.description}}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row meal-summary height-20">
                                        <div class="col">
                                            <p>
                                                £{{meal.price}}
                                            </p>
                                        </div>
                                        <div class="col">
                                            <div class = "{% if not meal.vegan and not meal.vegetarian %} transparent {% endif %}">
                                                {% if meal.vegan %} 
                                                    <div class="dark-circle-background white-text">
                                                        Ve
                                                    </div>
                                                {% endif %}
                                                {% if meal.vegetarian %}
                                                    <div class="dark-circle-background white-text">
                                                        V 
                                                    </div>
                                                {% endif %}
                                                {% if not meal.vegan and not meal.vegetarian %}
                                                    Has Meat
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}   
                {% endif%}
            {% endfor %}
        </div>
    </div>
{% endfor %}
</div>
</section>


{% endblock %}

meals/templates/Meals/meal_information.html
{% extends "base.html"%}
{% block content %}
{% load static %}

<section class = "margin-top-10vh  margin-bottom-10vh">
    <div class="container">
        <div class="row">
            <div class="col-sm d-flex justify-content-center margin-bottom-5vh">
                <img src="{{ meal_information.image.url }}" alt="{{ meal_information.name }}" class="min-height-width-300">
            </div>
            <div class="col-sm">
                <div class="row">
                    <div class="col">
                        <h2> {{meal_information.name}} </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p>
                            {{meal_information.description}}
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p class = "font-size-larger">Known Allergens</p>
                        <p>
                            {% for allergen in meal_information.allergens.all %}{{ allergen.name }}
                            <img src = "{{allergen.image.url}}" alt = "{{allergen.name}}" class = "width-height-32"><br/>
                            {% empty %}
                            None
                            {% endfor %}
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p class = "font-size-larger">Price</p>
                        <p>
                            £{{meal_information.price}}
                        </p>
                    </div>
                    <div class="col">
                        <p class = "font-size-larger">Calories</p>
                        <p>
                            {{meal_information.calories}} Kcal
                        </p>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</section>

{% endblock %}

meals/templates/Meals/meal_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<section class = "banner">
    <!--Photo by <a href="https://unsplash.com/@jaywennington?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jay Wennington</a> on <a href="https://unsplash.com/s/photos/restaurant?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  -->
    <div id = "full-menu-header" class="container">
        <div class="row margin-top-5vh">
            <div class="col-sm col-md4"></div>
            <div class="col-sm col-md4 d-flex align-items-center justify-content-center border-right-2 border-left-2">
                <h2 class = "text-align-center border-left-2px">Full Menu</h2>
            </div>
            <div class="col-sm col-md4"></div>
        
        </div>
    </div>
    <div class = "sticky-top">
        <div class="relative">
            <div class="container horizontal-scroll d-flex overflow-auto">
                {% for category in categories %}
                <a href="#{{ category.name}}">{{category.name}}</a>
                <div class="container">
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% for category in categories %}
    <div>
        <hr class="full-width-2px">
    </div>
    <div id = "{{category.name}}" class = "container-fluid d-flex align-items-center justify-content-center menu-category-background-generic {{category.name}}">
        <h1 class = "heading-font font-size-72">{{category.name}}</h1>
    </div>
    <div>
        <hr class="full-width-2px">
    </div>
    <div class="container">        
        <div class="row">
            {% for meal in meal_list %}
                {% if meal.category.name == category.name %}
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 col-xxl-4 menu-item">
                        <div class="row">
                            <div class="col-4 padding-0">
                                <a href="{% url 'meals:meal_information' meal.slug %}"><img src="{{meal.image.url}}" class="img-fluid menu-item-image" alt = "{{meal.name}}"></a>
                            </div>
                            <div class="col-8">
                                <div class="row height-20">
                                    <div class="col">
                                        <p>{{meal.name}}</p>
                                    </div>
                                </div>
                                <div class="row height-60">
                                    <div class="col">
                                        <p class = "description-overflow-scroll">
                                            {{meal.description}}
                                        </p>
                                    </div>
                                </div>
                                <div class="row meal-summary height-20">
                                    <div class="col">
                                        <p>
                                            £{{meal.price}}
                                        </p>
                                    </div>
                                    <div class="col">
                                        <div class = "{% if not meal.vegan and not meal.vegetarian %} transparent {% endif %}">
                                            {% if meal.vegan %} 
                                                <div class="dark-circle-background white-text">
                                                    Ve
                                                </div>
                                            {% endif %}
                                            {% if meal.vegetarian %}
                                                <div class="dark-circle-background white-text">
                                                    V 
                                                </div>
                                            {% endif %}
                                            {% if not meal.vegan and not meal.vegetarian %}
                                                Has Meat
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endfor %}
<div class="margin-bottom-10vh"></div>
{% endblock %}