about/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path

# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
    path('delete/<comment_id>', views.delete_item, name='delete'),
    path('edit/<comment_id>', views.edit_item, name='edit')
]

bookings/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'bookings'

urlpatterns = [
    path('', views.make_booking, name='make_booking'),
]

contact/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'contact'

urlpatterns = [
    path('', views.contact_us, name='contact_us'),
]

home/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

meals/urls.py
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Imports
# 3rd Party
from django.urls import path
# Internal
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Provide an app name to fix namespace error
app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('lunch_menu', views.lunch_menu, name='lunch_menu'),
    path('dinner_menu', views.dinner_menu, name='dinner_menu'),
    path('drinks_menu', views.drinks_menu, name='drinks_menu'),
    path('<slug>', views.meal_information, name='meal_information'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # connects the main urls with the app urls
    path('', include('home.urls', namespace='home')),
    path('meals/', include('meals.urls', namespace='meals')),
    path('make_booking/', include('bookings.urls', namespace='bookings')),
    path('contact_us/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name ="description" content= "Website for Eliginis Restaurant">
    <meta name ="keywords" content="Restaurant, Sutton Coldfield, Elginis, Italian food">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/acb51437a2.js" crossorigin="anonymous"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon_io/site.webmanifest' %}">
    <link href="{% static 'css/style.css' %}" rel = 'stylesheet' type = "text/css">
    <title>Eliginis Restaurant</title>
</head>
<body>
    <header>
        <!--Bootstrap Nav bar ammended with custom CSS-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <!--Brand logo in nav bar-->
                <a class="navbar-brand active heading-font margin-left-3vw white-text" href="{% url 'home:home' %}">elginis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'meals:meal_list' %}">Full Menu</a></li>
                                <li><a class="dropdown-item" href="{% url 'meals:lunch_menu' %}">Lunch Menu</a></li>
                                <li><a class="dropdown-item" href="{% url 'meals:dinner_menu' %}">Dinner Menu</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'meals:drinks_menu' %}">Drinks Menu</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about:about' %}">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact:contact_us' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:make_booking' %}">Reserve Table</a>
                        </li>
                        <!--Use all allauth in django to manage users and authentication-->
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">Login/Signup</a>
                            </li>
                        {% endif %}
                        </ul>
                    <!-- <form class="d-flex d-none d-lg-block d-xl-block d-xxl-block">
                        <button class="btn btn-outline-success" type="submit">Reserve Table</button>
                    </form> -->
                </div>
            </div>
        </nav>
    </header>

    {% block content %}


    {% endblock %}

    <footer>
        <ul class="navbar nav justify-content-center navbar-dark bg-dark white-text">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'contact:contact_us' %}">Talk to us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'meals:meal_list' %}">Menus</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookings:make_booking' %}"><span class = "d-sm-none">Book Table</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.instagram.com" rel="noopener noreferrer" target="_blank"><i class="fa fa-brands fa-instagram"></i><span class="sr-only">Instagram</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.facebook.com" rel="noopener noreferrer" target="_blank"><i class="fa fa-brands fa-facebook"></i><span class="sr-only">Facebook</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.twitter.com" rel="noopener noreferrer" target="_blank"><i class="fa fa-brands fa-twitter"></i><span class="sr-only">Twitter</span></a>
            </li>
        </ul>     
    </footer>
    {% block postloadjs %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>